kind: pipeline
name: deploy

steps:
  - name: submodules
    image: docker:git
    commands:
      - git submodule update --init --recursive
  - name: build-site
    image: garykim/hugo:0-extended
    pull: always
    commands:
      - make prod
  - name: prepare-deploy
    image: docker:git
    commands:
      - mv ./public /info.mcturtles.org/public
      - cp -r ./scripts /info.mcturtles.org/scripts
      - git clone https://github.com/gary-kim/info.mcturtles.org /info.mcturtles.org/repo
      - (cd /info.mcturtles.org/repo && git checkout gh-pages)
    volumes:
      - name: TMP
        path: /info.mcturtles.org
    when:
      branch:
        - master
      event:
        - push
      repo:
        - gary-kim/info.mcturtles.org
  - name: move-deploy
    image: garykim/rclone
    pull: always
    commands:
      - rclone sync /info.mcturtles.org/public /info.mcturtles.org/repo --exclude '.git/**'
    volumes:
      - name: TMP
        path: /info.mcturtles.org
    when:
      branch:
        - master
      event:
        - push
      repo:
        - gary-kim/info.mcturtles.org
  - name: push-deploy
    image: docker:git
    volumes:
      - name: TMP
        path: /info.mcturtles.org
    commands:
      - cd /info.mcturtles.org/repo
      - git add -A
      - GIT_COMMITTER_DATE="$(date)" git commit --author="Gary Kim <gary@garykim.dev>" --no-edit --amend --date "$(date)"
      - git -c "credential.helper=/bin/sh /info.mcturtles.org/scripts/gitcredentials.sh" push --force
    environment:
      GIT_PASSWORD:
        from_secret: GITHUB_TOKEN
      GIT_USERNAME: gary-kim-bot
      GIT_COMMITTER_NAME: gary-kim-bot
      GIT_COMMITTER_EMAIL: bot@garykim.dev
    when:
      branch:
        - master
      event:
        - push
      repo:
        - gary-kim/info.mcturtles.org

trigger:
  branch:
    - master
  event:
    - pull_request
    - push


volumes:
  - name: TMP
    temp: {}
