baseURL = "https://info.mcturtles.org/"
languageCode = "en-us"
title = "Minecraft: Turtle Server"
theme = "massively"
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

[[menus.main]]
    URL = "/about/"
    Name = "About"
    weight = 20
[[menus.main]]
    URL = "https://wiki.mcturtles.org/"
    Name = "Wiki"
    weight = 30
